# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7efab2bb5779476ef0b4c24fdafd348d5847cf006b9cac21852ea0f66dbf4083964484c2ab0cb9d110095ad97218120820a170d21aee435ac37295c902d8d18c

test:
  secret_key_base: 279442fa7fb6779ef686648fd3bc583ad5d7eb718b5f6666c9998186c771c2a4a1c3609ad4fe345ddacbb745be3f6d297c6a1c34bcccdff80f6f098e830f986e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
